### ISSUE TITLE
I can not use it with Ionic in Devices...

### ISSUE THREAD

**Issue by hughred22** [Stamplay/angular-stamplay#2]
So the JavaScript SDK and angular-stamplay cause CROS error: Failed to load resource: the server responded with a status of 403 (Forbidden). In the iOs simulator or actual devices, it is file://. So cross domain should not be an issue. But I still can not communicate with the stamplay server. Is there a way to make it work on devices so I can use it with Ionic framework and AngularJS?

**Comment by claudiopetrini** [comment]
Hi there,
to make it work with Ionic framework just use the port 8080.

**Comment by hughred22** [comment]
What do you mean using the port 8080? Setting in stamplay? When the app in actual devices or simulator, there is no port...

**Comment by claudiopetrini** [comment]
You can launch Ionic with
```
ionic serve -p 8080
```
If you need further assistance please join our [Slack community](https://slackinvites.stamplayapp.com/), since this is not an issue related to this repository I'm closing this issue.

**Comment by claudiopetrini** [comment]
When using simulator please add in the CORS field ```*```

**Comment by anujmpec** [comment]
Where to add ? In ajax call ?Give sample
